version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: artomily-app
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      REDIS_URL: ${REDIS_URL}
      ALIBABA_API_KEY: ${ALIBABA_API_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      TZ: Asia/Jakarta

    ports:
      - "3005:3000" # local debug tetap bisa

    expose:
      - "3000"
    networks:
      - app_internal
      - traefik_proxy

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.buatinai.rule=Host(`buatinai.radenalam.com`)"
      - "traefik.http.routers.buatinai.entrypoints=web"
      - "traefik.http.routers.buatinai.service=buatinai-svc"
      - "traefik.http.services.buatinai-svc.loadbalancer.server.port=3000"

  # Worker for BullMQ Job Processing
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    deploy:
      replicas: 2
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      ALIBABA_API_KEY: ${ALIBABA_API_KEY}
      TZ: Asia/Jakarta
    networks:
      - app_internal
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # optional: kalau worker butuh nunggu app/redis ready
    depends_on:
      - app

networks:
  app_internal:
    driver: bridge
  traefik_proxy:
    external: true
