import OpenAI from 'openai'
import { GenerationType, GenerationStatus } from '@prisma/client'

/**
 * AI Service - Handles interactions with Alibaba Cloud Model Studio
 * Uses Qwen for text generation and Wan for image/video generation
 * 
 * API Documentation: https://www.alibabacloud.com/help/en/model-studio/
 */

export interface TextGenerationOptions {
  prompt: string
  type: 'caption' | 'script' | 'copywriting'
  tone?: string
  language?: string
}

export interface ImageGenerationOptions {
  prompt: string
  style?: string
  aspectRatio?: string
  size?: string
  referenceImageUrl?: string // For image-to-image transformation
}

export interface VideoGenerationOptions {
  prompt: string
  duration?: number
  style?: string
  referenceImageUrl?: string // For image-to-video animation
}

export interface AIResult {
  success: boolean
  result?: string
  error?: string
  metadata?: Record<string, unknown>
}

// Alibaba Cloud Model Studio configuration
// Using Singapore (intl) region by default
const ALIBABA_BASE_URL = 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1'
const ALIBABA_API_URL = 'https://dashscope-intl.aliyuncs.com/api/v1'

// Model names
const TEXT_MODEL = 'qwen-plus' // Options: qwen-turbo, qwen-plus, qwen-max
const IMAGE_MODEL = 'wan2.6-t2i' // Wan 2.6 text-to-image
const IMAGE_EDIT_MODEL = 'qwen-image-edit-max' // Qwen Image Edit for image-to-image

// Get API key from environment
const getApiKey = () => {
  return process.env.ALIBABA_API_KEY || process.env.ALIBABA_DASHSCOPE_API_KEY
}

// Initialize OpenAI client for Alibaba Cloud (OpenAI-compatible mode)
const getQwenClient = () => {
  const apiKey = getApiKey()
  if (!apiKey) return null
  return new OpenAI({
    apiKey,
    baseURL: ALIBABA_BASE_URL,
  })
}

export class AIService {
  /**
   * Generate text content using Qwen (Alibaba Cloud)
   */
  static async generateText(options: TextGenerationOptions): Promise<AIResult> {
    const client = getQwenClient()

    // Fallback to mock if no API key
    if (!client) {
      console.log('No API key found, using mock for text generation')
      return this.generateTextMock(options)
    }

    try {
      const systemPrompts: Record<string, string> = {
        caption: `You are a creative social media expert. Generate engaging, culturally relevant captions for posts. 
Keep captions concise (under 200 characters when possible), include relevant hashtags, and make them shareable.
Consider cultural nuances and current trends. Respond with only the caption text.`,
        script: `You are a professional scriptwriter. Create engaging video scripts with clear scene directions.
Format scripts with scene headers, dialogue, and visual cues. Keep scripts concise and impactful.
Respond with only the script content.`,
        copywriting: `You are a skilled copywriter. Create compelling marketing copy that resonates with the target audience.
Focus on benefits, use persuasive language, and include clear calls-to-action.
Respond with only the copywriting content.`,
      }

      const tone = options.tone || 'professional'
      const language = options.language || 'English'

      console.log('Calling Qwen API for text generation...')

      const response = await client.chat.completions.create({
        model: TEXT_MODEL,
        messages: [
          {
            role: 'system',
            content: `${systemPrompts[options.type]}\n\nTone: ${tone}\nLanguage: ${language}`,
          },
          {
            role: 'user',
            content: options.prompt,
          },
        ],
        max_tokens: 1000,
        temperature: 0.7,
      })

      const result = response.choices[0]?.message?.content

      if (!result) {
        return { success: false, error: 'No response from Qwen' }
      }

      console.log('Qwen text generation successful')

      return {
        success: true,
        result,
        metadata: {
          model: TEXT_MODEL,
          provider: 'alibaba-qwen',
          characterCount: result.length,
          tokens: response.usage?.total_tokens,
        },
      }
    } catch (error) {
      console.error('Qwen text error:', error)
      // Fallback to mock on error
      return this.generateTextMock(options)
    }
  }

  /**
   * Mock text generation for development/fallback
   */
  private static async generateTextMock(options: TextGenerationOptions): Promise<AIResult> {
    await this.simulateProcessing(500)

    const mockResponses: Record<string, string> = {
      caption: `${options.prompt}\n\nThis is a culturally relevant caption that captures the essence of your message. #ArtomilyAI #CreativeContent`,
      script: `[SCENE START]\n\nNarrator: "${options.prompt}"\n\n[Visual: Engaging imagery that matches the cultural context]\n\n[SCENE END]\n\nGenerated by ArtomilyAI`,
      copywriting: `${options.prompt}\n\nTransform your brand's message with culturally-aware copywriting that resonates with your audience. Our AI understands local nuances and creates content that connects.`,
    }

    const result = mockResponses[options.type] || mockResponses.caption
    return {
      success: true,
      result,
      metadata: { model: 'mock', characterCount: result.length },
    }
  }

  /**
   * Generate image using Wan 2.6 (Alibaba Cloud)
   * Supports both text-to-image and image-to-image (with reference)
   * API Reference: https://www.alibabacloud.com/help/en/model-studio/text-to-image-v2-api-reference
   */
  static async generateImage(options: ImageGenerationOptions): Promise<AIResult> {
    const apiKey = getApiKey()

    // Fallback to mock if no API key
    if (!apiKey) {
      console.log('No API key found, using mock for image generation')
      return this.generateImageMock(options)
    }

    try {
      // Build enhanced prompt with style
      let stylePrompt = options.prompt
      if (options.style) {
        stylePrompt = `${options.prompt}, ${options.style} style`
      }

      // Determine size based on aspect ratio
      // Format: "width*height"
      let size = options.size || '1280*1280'
      if (options.aspectRatio === '16:9') size = '1696*960'
      if (options.aspectRatio === '9:16') size = '960*1696'
      if (options.aspectRatio === '4:3') size = '1472*1104'
      if (options.aspectRatio === '3:4') size = '1104*1472'

      console.log('Calling Wan API for image generation...')
      console.log('Prompt:', stylePrompt)
      console.log('Size:', size)
      console.log('Reference Image:', options.referenceImageUrl ? 'Provided' : 'None')

      // If reference image is provided, use image-to-image mode
      if (options.referenceImageUrl) {
        return await this.generateImageFromImage(options, apiKey, stylePrompt, size)
      }

      // Call Alibaba Cloud Wan text-to-image API (synchronous mode)
      const response = await fetch(`${ALIBABA_API_URL}/services/aigc/multimodal-generation/generation`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model: IMAGE_MODEL,
          input: {
            messages: [
              {
                role: 'user',
                content: [
                  {
                    text: stylePrompt,
                  },
                ],
              },
            ],
          },
          parameters: {
            prompt_extend: true,
            watermark: false,
            n: 1,
            negative_prompt: 'blurry, low quality, distorted, deformed, ugly, bad anatomy, oversaturated',
            size,
          },
        }),
      })

      if (!response.ok) {
        const errorText = await response.text()
        console.error('Alibaba image API error response:', errorText)
        let errorData
        try {
          errorData = JSON.parse(errorText)
        } catch {
          errorData = { message: errorText }
        }
        console.error('Alibaba image API error:', errorData)
        return this.generateImageMock(options)
      }

      const data = await response.json()
      console.log('Wan API response:', JSON.stringify(data, null, 2))

      // Extract image URL from response
      // Response format: output.choices[0].message.content[0].image
      const imageUrl = data.output?.choices?.[0]?.message?.content?.[0]?.image

      if (imageUrl) {
        console.log('Image generated successfully:', imageUrl.substring(0, 100) + '...')
        return {
          success: true,
          result: imageUrl,
          metadata: {
            model: IMAGE_MODEL,
            provider: 'alibaba-wan',
            size,
            mode: 'text-to-image',
            requestId: data.request_id,
          },
        }
      }

      console.error('No image URL in response:', data)
      return { success: false, error: 'No image generated' }
    } catch (error) {
      console.error('Wan image error:', error)
      return this.generateImageMock(options)
    }
  }

  /**
   * Generate image from reference image (Image-to-Image)
   * Uses Qwen-Image-Edit for transformation/editing
   * API Reference: https://www.alibabacloud.com/help/en/model-studio/qwen-image-edit
   */
  private static async generateImageFromImage(
    options: ImageGenerationOptions,
    apiKey: string,
    stylePrompt: string,
    size: string
  ): Promise<AIResult> {
    try {
      console.log('Using Image-to-Image mode with Qwen-Image-Edit...')

      // Qwen-Image-Edit uses the multimodal generation API
      // The image is provided as content, followed by text instruction
      const response = await fetch(`${ALIBABA_API_URL}/services/aigc/multimodal-generation/generation`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model: IMAGE_EDIT_MODEL,
          input: {
            messages: [
              {
                role: 'user',
                content: [
                  {
                    image: options.referenceImageUrl,
                  },
                  {
                    text: stylePrompt,
                  },
                ],
              },
            ],
          },
          parameters: {
            n: 1,
            prompt_extend: true,
            watermark: false,
            negative_prompt: 'blurry, low quality, distorted, deformed, ugly, bad anatomy',
            size,
          },
        }),
      })

      if (!response.ok) {
        const errorText = await response.text()
        console.error('Qwen Image Edit API error:', errorText)
        // Fallback to text-to-image
        return this.generateImage({ ...options, referenceImageUrl: undefined })
      }

      const data = await response.json()
      console.log('Qwen Image Edit response:', JSON.stringify(data, null, 2))

      // Response format: output.choices[0].message.content[0].image
      const imageUrl = data.output?.choices?.[0]?.message?.content?.[0]?.image

      if (imageUrl) {
        console.log('Image-to-Image successful')
        return {
          success: true,
          result: imageUrl,
          metadata: {
            model: IMAGE_EDIT_MODEL,
            provider: 'alibaba-qwen',
            size,
            mode: 'image-to-image',
            requestId: data.request_id,
          },
        }
      }

      return { success: false, error: 'Image transformation failed' }
    } catch (error) {
      console.error('I2I error:', error)
      // Fallback to regular generation
      return this.generateImage({ ...options, referenceImageUrl: undefined })
    }
  }

  /**
   * Mock image generation for development/fallback
   */
  private static async generateImageMock(options: ImageGenerationOptions): Promise<AIResult> {
    await this.simulateProcessing(1000)

    const seed = Math.floor(Math.random() * 1000)
    const result = `https://picsum.photos/seed/${seed}/1024/1024`

    return {
      success: true,
      result,
      metadata: { model: 'mock', dimensions: '1024x1024' },
    }
  }

  /**
   * Generate video using Wan (Alibaba Cloud)
   * Supports both text-to-video and image-to-video (with reference image)
   */
  static async generateVideo(options: VideoGenerationOptions): Promise<AIResult> {
    const apiKey = getApiKey()

    // Fallback to mock if no API key
    if (!apiKey) {
      console.log('No API key found, using mock for video generation')
      return this.generateVideoMock(options)
    }

    try {
      console.log('Calling Wan API for video generation...')
      console.log('Prompt:', options.prompt)
      console.log('Reference Image:', options.referenceImageUrl ? 'Provided' : 'None')

      // If reference image is provided, use image-to-video mode
      if (options.referenceImageUrl) {
        return await this.generateVideoFromImage(options, apiKey)
      }

      // Call Alibaba Cloud Wan text-to-video API
      // API Reference: https://www.alibabacloud.com/help/en/model-studio/text-to-video-api-reference
      const response = await fetch(`${ALIBABA_API_URL}/services/aigc/video-generation/video-synthesis`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
          'X-DashScope-Async': 'enable',
        },
        body: JSON.stringify({
          model: 'wan2.1-t2v-turbo',
          input: {
            prompt: options.prompt,
          },
          parameters: {
            size: '1280*720', // Text-to-video uses size, not resolution
            prompt_extend: true,
            duration: options.duration || 5,
          },
        }),
      })

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}))
        console.error('Alibaba video API error:', errorData)
        return this.generateVideoMock(options)
      }

      const data = await response.json()
      const taskId = data.output?.task_id

      if (!taskId) {
        return { success: false, error: 'No task ID returned' }
      }

      // Poll for video result
      return await this.pollVideoTask(taskId, apiKey, 'text-to-video')
    } catch (error) {
      console.error('Wan video error:', error)
      return this.generateVideoMock(options)
    }
  }

  /**
   * Generate video from reference image (Image-to-Video)
   * Animates a static image into a video
   * API Reference: https://www.alibabacloud.com/help/en/model-studio/image-to-video-api-reference
   */
  private static async generateVideoFromImage(
    options: VideoGenerationOptions,
    apiKey: string
  ): Promise<AIResult> {
    try {
      console.log('Using Image-to-Video mode...')

      // Call image-to-video API (same endpoint as text-to-video)
      const response = await fetch(`${ALIBABA_API_URL}/services/aigc/video-generation/video-synthesis`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
          'X-DashScope-Async': 'enable',
        },
        body: JSON.stringify({
          model: 'wan2.1-i2v-plus', // Image-to-video model
          input: {
            prompt: options.prompt,
            img_url: options.referenceImageUrl, // Must be img_url, not image_url
          },
          parameters: {
            resolution: '720P',
            prompt_extend: true,
            duration: options.duration || 5,
          },
        }),
      })

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}))
        console.error('Alibaba I2V API error:', errorData)
        // Fallback to text-to-video
        return this.generateVideo({ ...options, referenceImageUrl: undefined })
      }

      const data = await response.json()
      const taskId = data.output?.task_id

      if (!taskId) {
        return { success: false, error: 'No task ID returned for I2V' }
      }

      // Poll for video result
      return await this.pollVideoTask(taskId, apiKey, 'image-to-video')
    } catch (error) {
      console.error('I2V error:', error)
      // Fallback to text-to-video
      return this.generateVideo({ ...options, referenceImageUrl: undefined })
    }
  }

  /**
   * Poll for async video generation task result
   */
  private static async pollVideoTask(taskId: string, apiKey: string, mode: string = 'text-to-video'): Promise<AIResult> {
    const maxAttempts = 120 // 10 minutes max (5s intervals)

    for (let i = 0; i < maxAttempts; i++) {
      await this.simulateProcessing(5000)

      try {
        // Poll video-synthesis task status
        const response = await fetch(`${ALIBABA_API_URL}/services/aigc/video-generation/video-synthesis/${taskId}`, {
          headers: {
            'Authorization': `Bearer ${apiKey}`,
          },
        })

        if (!response.ok) continue

        const data = await response.json()
        console.log(`Video poll attempt ${i + 1}:`, data.output?.task_status)

        const status = data.output?.task_status

        if (status === 'SUCCEEDED') {
          const videoUrl = data.output?.video_url
          if (videoUrl) {
            return {
              success: true,
              result: videoUrl,
              metadata: {
                model: mode === 'image-to-video' ? 'wan2.1-i2v-plus' : 'wan2.1-t2v-turbo',
                provider: 'alibaba-wan',
                mode,
                taskId,
                duration: data.output?.duration,
              },
            }
          }
        } else if (status === 'FAILED') {
          return { success: false, error: data.message || 'Video generation failed' }
        }
      } catch (err) {
        console.error('Video poll error:', err)
      }
    }

    return { success: false, error: 'Video generation timeout' }
  }

  /**
   * Mock video generation for development/fallback
   */
  private static async generateVideoMock(options: VideoGenerationOptions): Promise<AIResult> {
    await this.simulateProcessing(2000)

    const result = `https://example.com/mock-video-${Date.now()}.mp4`

    return {
      success: true,
      result,
      metadata: { model: 'mock', duration: options.duration || 4 },
    }
  }

  /**
   * Upscale image using Alibaba Cloud
   */
  static async upscaleImage(imageUrl: string): Promise<AIResult> {
    const apiKey = getApiKey()

    // Fallback to mock if no API key
    if (!apiKey) {
      console.log('No API key found, using mock for upscale')
      return this.upscaleImageMock(imageUrl)
    }

    try {
      console.log('Calling API for image upscale...')

      // Use image super-resolution API
      const response = await fetch(`${ALIBABA_API_URL}/services/aigc/image-super-resolution`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model: 'image-super-resolution',
          input: {
            image_url: imageUrl,
          },
          parameters: {
            scale: 2,
          },
        }),
      })

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}))
        console.error('Alibaba upscale API error:', errorData)
        return this.upscaleImageMock(imageUrl)
      }

      const data = await response.json()

      if (data.output?.image_url) {
        return {
          success: true,
          result: data.output.image_url,
          metadata: {
            model: 'image-super-resolution',
            provider: 'alibaba',
            scale: '2x',
          },
        }
      }

      return { success: false, error: 'Upscale failed' }
    } catch (error) {
      console.error('Upscale error:', error)
      return this.upscaleImageMock(imageUrl)
    }
  }

  /**
   * Mock upscale for development/fallback
   */
  private static async upscaleImageMock(imageUrl: string): Promise<AIResult> {
    await this.simulateProcessing(500)

    return {
      success: true,
      result: imageUrl.replace('/1024/1024', '/2048/2048'),
      metadata: { model: 'mock', scale: '2x' },
    }
  }

  /**
   * Process generation based on type
   */
  static async processGeneration(
    type: GenerationType,
    prompt: string,
    generationId: string,
    options?: {
      textType?: 'caption' | 'script' | 'copywriting'
      imageStyle?: string
      aspectRatio?: string
    }
  ): Promise<AIResult> {
    const { GenerationService } = await import('./generation.service')

    try {
      await GenerationService.updateGeneration(generationId, {
        status: GenerationStatus.PROCESSING,
      })

      let result: AIResult

      switch (type) {
        case 'TEXT':
          result = await this.generateText({
            prompt,
            type: options?.textType || 'caption',
          })
          break

        case 'IMAGE':
          result = await this.generateImage({
            prompt,
            style: options?.imageStyle,
            aspectRatio: options?.aspectRatio,
          })
          break

        case 'VIDEO':
          result = await this.generateVideo({ prompt })
          break

        case 'UPSCALE':
          result = await this.upscaleImage(prompt)
          break

        default:
          throw new Error(`Unknown generation type: ${type}`)
      }

      if (result.success && result.result) {
        await GenerationService.completeGeneration(generationId, result.result, result.metadata)
      } else {
        await GenerationService.failGeneration(generationId, result.error || 'Generation failed')
      }

      return result
    } catch (error) {
      await GenerationService.failGeneration(
        generationId,
        error instanceof Error ? error.message : 'Generation failed'
      )
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Generation failed',
      }
    }
  }

  /**
   * Simulate processing delay for mock implementations
   */
  private static simulateProcessing(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms))
  }
}
